name: Helm Release

on:
  push:
    branches:
      - master

jobs:
  release-helm-chart:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Helm Lint
        run: helm lint charts/casdoor

      - name: Run helm unittest
        id: unittest
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
          helm unittest charts/casdoor

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Release Helm Chart
        run: |
          REGISTRY=oci://registry-1.docker.io/casbin
          cd charts/casdoor
          helm package .
          PKG_NAME=$(ls *.tgz)
          helm repo index . --url $REGISTRY --merge index.yaml
          helm push $PKG_NAME $REGISTRY
          rm $PKG_NAME